## Tensor and Autograd

### Rank(Dimension)
- Rank == 0 : Scalar, Example: 1 / The shape is [] 
- Rank == 1 : Vector, Example: [1, 2, 3] / The shape is [3]
- Rank == 2 : Matrix, Example: [[1, 2, 3]] / The shape is [1, 3]
- Rank == 3 : Tensor, Example: [[[1, 2, 3]]] / The shape is [1, 1, 3]
- Rank >= 3 : Rank N Tensor

## 1. Create first tensor

In [2]:
import torch

In [4]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [11]:
print(f'size is {x.size()}')
print(f'shape is {x.shape}')
print(f'rank(dimension) is {x.ndimension()}')

size is torch.Size([3, 3])
shape is torch.Size([3, 3])
rank(dimension) is 2


### 1_1. 차원(Rank) 늘리기 & 줄이기
- torch.unsqueeze(x, 0): 텐서 x의 첫 번째(0번째) 자리에 1이라는 차원값을 추가해서 랭크를 늘림
- torch.squeeze(x): 텐서의 랭크 중 크기가 1인 랭크를 삭제하여 랭크를 줄임

In [12]:
x = torch.unsqueeze(x, 0)
print(x)
print(f'size is {x.size()}')
print(f'shape is {x.shape}')
print(f'rank(dimension) is {x.ndimension()}')

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
size is torch.Size([1, 3, 3])
shape is torch.Size([1, 3, 3])
rank(dimension) is 3


In [13]:
x = torch.squeeze(x)
print(x)
print(f'size is {x.size()}')
print(f'shape is {x.shape}')
print(f'rank(dimension) is {x.ndimension()}')

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
size is torch.Size([3, 3])
shape is torch.Size([3, 3])
rank(dimension) is 2


### 1_2. View() function

In [14]:
try:
    x = x.view(2, 4)
except Exception as e:
    print(e)

shape '[2, 4]' is invalid for input of size 9


현재 3x3 shape를 가진 tensor로, 총 원소의 개수인데 2x4 shape로 바꿀 수는 없음

In [18]:
try:
    x = x.view(9)
    print(x)
    print(f'size is {x.size()}')
    print(f'shape is {x.shape}')
    print(f'rank(dimension) is {x.ndimension()}')
except Exception as e:
    print(e)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
size is torch.Size([9])
shape is torch.Size([9])
rank(dimension) is 1


### 1_3. Calculation & Matrix Multiplication using Tensor
- torch.randn(x_shape, y_shape, data_type): 정규분포(normal distribution)에서 무작위로 값을 뽑아 텐서를 생성하는 함수

In [21]:
w = torch.randn(5, 3, dtype=torch.float) # 5 x 3 matrix
x = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0],
                  [5.0, 6.0]]) # 3 x 2 matrix
print(f'w size is {w.shape}')
print(f'x size is {x.shape}')
print(f'w: {w}')
print(f'x: {x}')

w size is torch.Size([5, 3])
x size is torch.Size([3, 2])
w: tensor([[ 0.1997,  1.2069,  1.2695],
        [-0.7289,  1.2815,  0.3102],
        [ 1.1469, -0.4120,  1.2758],
        [ 0.4100, -0.2820, -0.6695],
        [ 0.1483, -0.0654, -2.1385]])
x: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [22]:
b = torch.randn(5, 2, dtype=torch.float)
print(f'b size is {b.shape}')
print(f'b: {b}')

b size is torch.Size([5, 2])
b: tensor([[-1.4106,  1.3719],
        [-0.8245,  2.3801],
        [-1.0588,  1.6728],
        [ 0.7171, -0.8105],
        [ 0.9597,  0.3023]])


#### Matrix Multiplication == torch.mm()

In [23]:
wx = torch.mm(w, x)
print(f'wx size is {wx.shape}') # (5 x 3) * (3 x 2) = (5 x 2) matrix
print(f'wx: {wx}')

wx size is torch.Size([5, 2])
wx: tensor([[ 10.1677,  12.8437],
        [  4.6664,   5.5292],
        [  6.2898,   8.3005],
        [ -3.7833,  -4.3247],
        [-10.7405, -12.7961]])


#### Add Calculation

In [24]:
result = wx + b
print(f'result size is {result.shape}')
print(f'result: {result}')

result size is torch.Size([5, 2])
result: tensor([[  8.7570,  14.2156],
        [  3.8420,   7.9093],
        [  5.2310,   9.9733],
        [ -3.0661,  -5.1352],
        [ -9.7808, -12.4938]])


## 2. Autograd
#### Background knowledge
- 오차(loss): 모델이 예측한 값과 실제값(ground truth)와의 차이(거리)의 평균. 즉, 오차가 작을수록 성능이 좋은 모델
- 경사하강법(gradient descent): 오차를 수학 함수로 표현한 후 편미분하여 함수의 기울기(gradient)를 구해 오차의 최솟값이 있는 방향을 찾아내는 알고리즘으로써, 가장 유명하고 많이 쓰임

#### Why does it use?
- 복잡한 인공 신경망 모델에서 일일이 NumPy를 활용해서 복잡한 계산을 여러 번하는 것이 번거롭기 때문에 미분 계산을 자동화해주는 autograd를 사용

In [25]:
w = torch.tensor(1.0, requires_grad=True)

In [26]:
a = w*3

In [29]:
l = a**2 # 미분하기 위해서는 chain rule을 이용하여 a와 w를 차례대로 미분해야 함 - 이를 위해서 backward() 함수 사용

#### l = a^2 = (3w)^2 = 9w^2

In [30]:
l.backward()
print(f'l을 w로 미분한 값은 {w.grad}')

l을 w로 미분한 값은 18.0
